package com.devtiro.database.controllers;

import com.devtiro.database.TestDataUtil;
import com.devtiro.database.domain.dto.AuthorDto;
import com.devtiro.database.domain.entities.AuthorEntity;
import com.devtiro.database.services.AuthorService;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

@SpringBootTest
@ExtendWith(SpringExtension.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@AutoConfigureMockMvc   //Creates instances of MockMVC and places in our TestContext, suited for Controllers
public class AuthorControllerIntegrationTests {

  private AuthorService authorService;

  private MockMvc mockMvc;

  private ObjectMapper objectMapper;

  @Autowired
  public AuthorControllerIntegrationTests(AuthorService authorService, MockMvc mockMvc, ObjectMapper objectMapper) {
    this.authorService = authorService;
    this.mockMvc = mockMvc;
    this.objectMapper = objectMapper;
  }


  @Test
  public void testThatCreateAuthorSuccessfullyReturnsHttp201Created() throws Exception {
    /* 'Exception' is needed for MockMvn, and already handles:
         JsonProcessingException (needed for objectMapper.writeValueAsString)) */
    AuthorEntity testAuthorEntityA = TestDataUtil.createTestAuthorEntityA();
    testAuthorEntityA.setId(null);  //id is autogenerated
    String authorJson = objectMapper.writeValueAsString(testAuthorEntityA);//convert to JSON

    mockMvc.perform(
        MockMvcRequestBuilders
            .post("/authors")
            .contentType(MediaType.APPLICATION_JSON)
            .content(authorJson)  //for the RequestBody, .content("json String")
    ).andExpect(    //this is how you add assertions; and you need a ResultMatcher
        MockMvcResultMatchers.status().isCreated()
    );
  }

  @Test
  public void testThatCreateAuthorSuccessfullyReturnsSavedAuthor() throws Exception {
    AuthorEntity testAuthorEntityA = TestDataUtil.createTestAuthorEntityA();
    testAuthorEntityA.setId(null);
    String authorJson = objectMapper.writeValueAsString(testAuthorEntityA);

    mockMvc.perform(
        MockMvcRequestBuilders
            .post("/authors")
            .contentType(MediaType.APPLICATION_JSON)
            .content(authorJson)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").isNumber()
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value("80")
    );
  }

  //To test the ReadMany endpoint(List), return status
  @Test
  public void testThatListAuthorsReturnsStatusHttp200() throws Exception {
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isOk()
    );
  }

  //To test the ReadMany endpoint(List), return status
  @Test
  public void testThatListAuthorsSuccessfullyReturnsListOfAuthors() throws Exception {
    AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(author);

    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].id").isNumber()
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].age").value("80")
    );
  }

  @Test
  public void testThatGetAuthorReturnsHttpStatus200WhenAuthorExists() throws Exception {
    //What do I need to test the findOne end-point? What does it do? Create one to retrieve it
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(testAuthorEntity);

    //2.Retrieve: API http get
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isOk()
    );
  }

  @Test
  public void testThatGetAuthorReturnsHttpStatus404WhenNoAuthorExists() throws Exception {
    //2.Retrieve: API http get
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isNotFound()
    );
  }

  @Test
  public void testThatGetAuthorsReturnsAuthorsWhenAuthorExists() throws Exception {
    AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(author);

    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").value(1)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value("80")
    );
  }

  @Test
  public void testThatFullUpdateAuthorReturnsHttpStatus200() throws Exception {
    //1.find the author to be Updated
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(testAuthorEntity);
    //2.get the modification to send, in Json
    testAuthorEntity.setName("J. J. Smith");
    testAuthorEntity.setAge(99);
    String testAuthorJson = objectMapper.writeValueAsString(testAuthorEntity); //throws JsonProcessingException
//3.then make the request to the update
    mockMvc.perform(    //throws Exception, which is more general, so also covers JsonProcessingException
        MockMvcRequestBuilders
            .put("/authors/" + testAuthorEntity.getId())
            .contentType(MediaType.APPLICATION_JSON)
            .content(testAuthorJson)
    ).andExpect(
        MockMvcResultMatchers.status().isOk()
    );
  }

  @Test
  public void testThatFullUpdateAuthorReturnsHttpStatus404WhenNoAuthorExists() throws Exception {
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    String testAuthorJson = objectMapper.writeValueAsString(testAuthorEntity);//throws JsonProcessingException

    mockMvc.perform(    //throws Exception, which is more general, so also covers JsonProcessingException
        MockMvcRequestBuilders
            .put("/authors/99")
            .contentType(MediaType.APPLICATION_JSON)
            .content(testAuthorJson)
    ).andExpect(
        MockMvcResultMatchers.status().isNotFound()
    );
  }

  @Test
  public void testThatFullUpdateAuthorReturnsFullyUpdatedAuthor() throws Exception {
    //1.find the author to be Updated
    AuthorEntity testAuthorEntityC = TestDataUtil.createTestAuthorC();
    AuthorEntity savedAuthorC = authorService.createAuthor(testAuthorEntityC);
    //2.get the modification to send, in Json
    AuthorDto authorDtoA = TestDataUtil.createTestAuthorDtoA();
    authorDtoA.setId(savedAuthorC.getId());
    String authorDtoUpdateJson = objectMapper.writeValueAsString(authorDtoA);//throws JsonProcessingException
    //3.then make the request to the update
    mockMvc.perform(    //throws Exception, which is more general, so also covers JsonProcessingException
        MockMvcRequestBuilders
            .put("/authors/" + savedAuthorC.getId())
            .contentType(MediaType.APPLICATION_JSON)
            .content(authorDtoUpdateJson)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").value(savedAuthorC.getId())
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value(authorDtoA.getName())
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value(authorDtoA.getAge())
    );
  }

  @Test
  public void testThatPartialUpdateAuthorReturnsHttpStatus200WhenAuthorExists() throws Exception {
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    AuthorEntity savedAuthor = authorService.createAuthor(testAuthorEntity);

    AuthorDto testAuthorDto = TestDataUtil.createTestAuthorDtoA();
     testAuthorDto.setName("UPDATED");
    String testAuthorJson = objectMapper.writeValueAsString(testAuthorDto);

    mockMvc.perform(
        MockMvcRequestBuilders
            .put("/authors/" + savedAuthor.getId())
            .contentType(MediaType.APPLICATION_JSON)
            .content(testAuthorJson)
    ).andExpect( MockMvcResultMatchers.status().isOk() );
  }

  @Test
  public void testThatPartialUpdateAuthorReturnsUpdatedAuthorWhenAuthorExists() throws Exception {
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    AuthorEntity savedAuthor = authorService.createAuthor(testAuthorEntity);

    AuthorDto testAuthorDto = TestDataUtil.createTestAuthorDtoA();
    testAuthorDto.setName("UPDATED");
    String testAuthorJson = objectMapper.writeValueAsString(testAuthorDto);

    mockMvc.perform(
        MockMvcRequestBuilders
            .put("/authors/" + savedAuthor.getId())
            .contentType(MediaType.APPLICATION_JSON)
            .content(testAuthorJson)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").value(savedAuthor.getId())
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value("UPDATED")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value(testAuthorDto.getAge())
    );
  }

  //Becuase if the author doesn't exist it still won't exist...
  @Test
  public void testThatAuthorDeleteReturnsHttpResponse204WhenNoAuthorExists() throws Exception {
    mockMvc.perform(
        MockMvcRequestBuilders
            .delete("/authors/99")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isNoContent()
    );
  }

  @Test
  public void testThatAuthorDeleteReturnsHttpResponse204WhenAuthorDeleted() throws Exception {
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    AuthorEntity savedAuthor = authorService.createAuthor(testAuthorEntity);

    mockMvc.perform(
        MockMvcRequestBuilders
              .delete("/authors/" + savedAuthor.getId())
              .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isNoContent()
    );
  }

}
