package com.devtiro.database.controllers;

import com.devtiro.database.TestDataUtil;
import com.devtiro.database.domain.entities.AuthorEntity;
import com.devtiro.database.services.AuthorService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

@SpringBootTest
@ExtendWith(SpringExtension.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
@AutoConfigureMockMvc   //Creates instances of MockMVC and places in our TestContext, suited for Controllers
public class AuthorControllerIntegrationTests {

  private AuthorService authorService;

  private MockMvc mockMvc;

  private ObjectMapper objectMapper;

  @Autowired
  public AuthorControllerIntegrationTests(AuthorService authorService, MockMvc mockMvc, ObjectMapper objectMapper) {
    this.authorService = authorService;
    this.mockMvc = mockMvc;
    this.objectMapper = objectMapper;
  }


  @Test
  public void testThatCreateAuthorSuccessfullyReturnsHttp201Created() throws Exception {
    /* 'Exception' is needed for MockMvn, and already handles:
         JsonProcessingException (needed for objectMapper.writeValueAsString)) */
    AuthorEntity testAuthorEntityA = TestDataUtil.createTestAuthorEntityA();
    testAuthorEntityA.setId(null);  //id is autogenerated
    String authorJson = objectMapper.writeValueAsString(testAuthorEntityA);//convert to JSON

    mockMvc.perform(
        MockMvcRequestBuilders
            .post("/authors")
            .contentType(MediaType.APPLICATION_JSON)
            .content(authorJson)  //for the RequestBody, .content("json String")
    ).andExpect(    //this is how you add assertions; and you need a ResultMatcher
        MockMvcResultMatchers.status().isCreated()
    );
  }

  @Test
  public void testThatCreateAuthorSuccessfullyReturnsSavedAuthor() throws Exception {
    AuthorEntity testAuthorEntityA = TestDataUtil.createTestAuthorEntityA();
    testAuthorEntityA.setId(null);
    String authorJson = objectMapper.writeValueAsString(testAuthorEntityA);

    mockMvc.perform(
        MockMvcRequestBuilders
            .post("/authors")
            .contentType(MediaType.APPLICATION_JSON)
            .content(authorJson)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").isNumber()
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value("80")
    );
  }

  //To test the ReadMany endpoint(List), return status
  @Test
  public void testThatListAuthorsReturnsStatusHttp200() throws Exception {
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isOk()
    );
  }

  //To test the ReadMany endpoint(List), return status
  @Test
  public void testThatListAuthorsSuccessfullyReturnsListOfAuthors() throws Exception {
    AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(author);

    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].id").isNumber()
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$[0].age").value("80")
    );
  }

  @Test
  public void testThatGetAuthorReturnsHttpStatus200WhenAuthorExists() throws Exception {
    //What do I need to test the findOne end-point? What does it do? Create one to retrieve it
    AuthorEntity testAuthorEntity = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(testAuthorEntity);

    //2.Retrieve: API http get
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isOk()
    );
  }

  @Test
  public void testThatGetAuthorReturnsHttpStatus404WhenNoAuthorExists() throws Exception {
    //2.Retrieve: API http get
    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.status().isNotFound()
    );
  }

  @Test
  public void testThatGetAuthorsReturnsAuthorsWhenAuthorExists() throws Exception {
    AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
    authorService.createAuthor(author);

    mockMvc.perform(
        MockMvcRequestBuilders
            .get("/authors/1")
            .contentType(MediaType.APPLICATION_JSON)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.id").value(1)
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.name").value("Abigail Rose")
    ).andExpect(
        MockMvcResultMatchers.jsonPath("$.age").value("80")
    );
  }

}
